services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: always
